/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -I/media/data/vmshare/bitbucket/framework/src/nim_app/../common/framework -o /media/data/vmshare/bitbucket/framework/src/nim_app/nimcache/framework.o /media/data/vmshare/bitbucket/framework/src/nim_app/nimcache/framework.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include "camera.h"
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NIMCALL(void, TMP146)(void* p, NI op);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI90203; /* Camera */
extern TNimType NTI5817; /* cfloat */
extern TNimType NTI5811; /* cint */
TNimType NTI91011; /* ref Camera */
extern TFrame* frameptr_17042;
N_NIMCALL(void, TMP146)(void* p, NI op) {
	Camera* a;
	a = (Camera*)p;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_frameworkInit)(void) {
	nimfr("framework", "framework.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_frameworkDatInit)(void) {
static TNimNode* TMP145[4];
static TNimNode TMP143[5];
NTI90203.size = sizeof(Camera);
NTI90203.kind = 18;
NTI90203.base = 0;
NTI90203.flags = 3;
TMP145[0] = &TMP143[1];
TMP143[1].kind = 1;
TMP143[1].offset = offsetof(Camera, posX);
TMP143[1].typ = (&NTI5817);
TMP143[1].name = "posX";
TMP145[1] = &TMP143[2];
TMP143[2].kind = 1;
TMP143[2].offset = offsetof(Camera, posY);
TMP143[2].typ = (&NTI5817);
TMP143[2].name = "posY";
TMP145[2] = &TMP143[3];
TMP143[3].kind = 1;
TMP143[3].offset = offsetof(Camera, width);
TMP143[3].typ = (&NTI5811);
TMP143[3].name = "width";
TMP145[3] = &TMP143[4];
TMP143[4].kind = 1;
TMP143[4].offset = offsetof(Camera, height);
TMP143[4].typ = (&NTI5811);
TMP143[4].name = "height";
TMP143[0].len = 4; TMP143[0].kind = 2; TMP143[0].sons = &TMP145[0];
NTI90203.node = &TMP143[0];
NTI91011.size = sizeof(Camera*);
NTI91011.kind = 22;
NTI91011.base = (&NTI90203);
NTI91011.flags = 2;
NTI91011.marker = TMP146;
}

