/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -I../common/framework -o /media/data/vmshare/bitbucket/framework/src/nim_app/nimcache/nimapp.o /media/data/vmshare/bitbucket/framework/src/nim_app/nimcache/nimapp.h */
#ifndef __nimapp__
#define __nimapp__
#define NIM_INTBITS 64
#include "nimbase.h"
N_NOCONV(void, signalHandler)(int sig);
N_NIMCALL(NI, getRefcount)(void* p);
N_NIMCALL(void, nimInit)(int appwassuspended);
N_NIMCALL(int, nimDoFrame)(int tick);
N_CDECL(void, NimMain)(void);
#endif /* __nimapp__ */
