/* Generated by Nim Compiler v0.11.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /media/data/vmshare/bitbucket/framework/src/nim_app/nimcache/nimapp.o /media/data/vmshare/bitbucket/framework/src/nim_app/nimcache/nimapp.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(int, fib)(int a);
N_NIMCALL(NimStringDesc*, readline_13478)(FILE* f);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimappInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimappDatInit)(void);
STRING_LITERAL(TMP141, "What\'s your name? ", 18);
STRING_LITERAL(TMP142, "Hi, ", 4);
STRING_LITERAL(TMP143, "!", 1);
extern TFrame* frameptr_17042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(int, fib)(int a) {
	int result;
	NimStringDesc* name;
	nimfr("fib", "nimapp.nim")
	result = 0;
	nimln(2, "nimapp.nim");
	printf("%s\012", ((NimStringDesc*) &TMP141)? (((NimStringDesc*) &TMP141))->data:"nil");
	nimln(3, "nimapp.nim");
	name = readline_13478(stdin);
	nimln(4, "nimapp.nim");
	printf("%s%s%s\012", ((NimStringDesc*) &TMP142)? (((NimStringDesc*) &TMP142))->data:"nil", name? (name)->data:"nil", ((NimStringDesc*) &TMP143)? (((NimStringDesc*) &TMP143))->data:"nil");
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	nimappDatInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	nimappInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

NIM_EXTERNC N_NOINLINE(void, nimappInit)(void) {
	nimfr("nimapp", "nimapp.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimappDatInit)(void) {
}

