/* Generated by Nim Compiler v0.11.2 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -I/media/data/vmshare/bitbucket/framework/src/nim_app/../common/framework -o /media/data/vmshare/bitbucket/framework/src/nim_app/nimcache/nimapp.o /media/data/vmshare/bitbucket/framework/src/nim_app/nimcache/nimapp.c */
#define NIM_INTBITS 64
#include "nimbase.h"
N_NIMCALL(void, nimInit)(int appwassuspended);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_20001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(int, nimDoFrame)(int tick);
N_NIMCALL(void, update_91048)(NI tick);
N_NIMCALL(void, draw_91034)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_frameworkInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_frameworkDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_app_mainInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_app_mainDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimappInit)(void);
NIM_EXTERNC N_NOINLINE(void, nimappDatInit)(void);
extern TFrame* frameptr_17042;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_17042 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_17042).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_17042;
	frameptr_17042 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_20001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_17042 = (*frameptr_17042).prev;
}

N_NIMCALL(void, nimInit)(int appwassuspended) {
	nimfr("nimInit", "nimapp.nim")
{	nimln(3, "nimapp.nim");
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(int, nimDoFrame)(int tick) {
	int result;
	nimfr("nimDoFrame", "nimapp.nim")
{	result = 0;
	nimln(7, "nimapp.nim");
	update_91048(((NI) (tick)));
	nimln(8, "nimapp.nim");
	draw_91034();
	nimln(9, "nimapp.nim");
	result = ((int) 0);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	HEX00_frameworkDatInit();
	HEX00_app_mainDatInit();
	nimappDatInit();
	HEX00_frameworkInit();
	HEX00_app_mainInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	nimappInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

NIM_EXTERNC N_NOINLINE(void, nimappInit)(void) {
	nimfr("nimapp", "nimapp.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimappDatInit)(void) {
}

